import { Blinker } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import { PageContextProvider } from "@/contexts/PageContext";

const blinker = Blinker({
  variable: "--font-blinker",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "600", "700", "800"],
});

const bolde = localFont({
  src: [
    {
      path: "../fonts/BOLDE.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-bolde",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${blinker.variable} ${bolde.variable} antialiased`}>
        <PageContextProvider>
          <Navbar />
          <Sidebar />
          <main className="pt-20 w-full min-h-screen flex flex-col relative">
            <div className="w-full max-w-[1600px] mx-auto flex-1">
              {children}
            </div>
          <Footer />
          </main>
        </PageContextProvider>
      </body>
    </html>
  );
}
